/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./../components/board.vue')['default']
    Cell: typeof import('./../components/cell.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfig: typeof import('naive-ui')['NConfig']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    Overlay: typeof import('./../components/overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
